#define LOCALDEF static
#define LOCALDEC static
#ifndef OMIT_ANYCHAN
#include "TiNGanyevent.c"
#endif
#include "TiNGcommon.c"
#include "TiNGconf.c"
#include "TiNGdetect.c"
#include "TiNGevent.c"
#include "TiNGgenlib.c"
#include "TiNGglobal.c"
#include "TiNGiwr.c"
#include "TiNGo_card.c"
#include "TiNGo_cardmap.c"
#include "TiNGo_chan.c"
#include "TiNGo_coll.c"
#include "TiNGo_disp.c"
#include "TiNGo_i460mux.c"
#include "TiNGo_framer.c"
#include "TiNGo_mod.c"
#include "TiNGo_path.c"
#include "TiNGo_tdmrx.c"
#include "TiNGo_tdmtx.c"
#include "TiNGi460lib.c"
#include "TiNGframerlib.c"
#include "TiNGpath.c"
#include "TiNGsmbesp.c"
#include "TiNGsmdc.c"
#include "TiNGsmdc_async.c"
#include "TiNGsmdc_bulkrx.c"
#include "TiNGsmdc_cpu.c"
#include "TiNGsmdc_cwrx.c"
#include "TiNGsmdc_cwtx.c"
#include "TiNGsmdc_fskrx.c"
#include "TiNGsmdc_fsktx.c"
#include "TiNGsmdc_hdlc.c"
#include "TiNGsmdc_heap.c"
#include "TiNGsmdc_ifprx.c"
#include "TiNGsmdc_ifptx.c"
#include "TiNGsmdc_none.c"
#include "TiNGsmdc_rawrx.c"
#include "TiNGsmdc_rawtx.c"
#include "TiNGsmdc_rdbg.c"
#include "TiNGsmdc_rlprx.c"
#include "TiNGsmdc_rlptx.c"
#include "TiNGsmdc_speech.c"
#include "TiNGsmdc_sync.c"
#include "TiNGsmdc_ttyrx.c"
#include "TiNGsmdc_v110.c"
#include "TiNGsmdc_v17rx.c"
#include "TiNGsmdc_v17tx.c"
#include "TiNGsmdc_v27rx.c"
#include "TiNGsmdc_v27tx.c"
#include "TiNGsmdc_v29rx.c"
#include "TiNGsmdc_v29tx.c"
#include "TiNGsmdc_v32.c"
#include "TiNGsmdc_v34.c"
#include "TiNGsmtone.c"
#include "TiNGsync.c"
#include "confmask.c"
#include "globaltime.c"
#include "iir4.c"
#include "paranoia.c"
#include "smbesp.c"
#include "smdc.c"
#include "smdc_encode.c"
#include "smgroove.c"
#include "trace.c"
#include "trace_gen_show.c"
#include "trace_smbesp_show.c"
#include "trace_smdc_show.c"

#ifdef TiNGTYPE_LINUX
#include "POSIX/condvar.c"
#include "POSIX/errcode.c"
#include "POSIX/event.c"
#include "POSIX/mutx.c"
#include "POSIX/once.c"
#endif

#ifdef TiNGTYPE_QNX
#include "POSIX/condvar.c"
#include "POSIX/errcode.c"
#include "POSIX/event.c"
#include "POSIX/mutx.c"
#include "POSIX/once.c"
#endif

#ifdef TiNGTYPE_WINNT
#include "WINNT/condvar.c"
#include "WINNT/errcode.c"
#include "WINNT/event.c"
#include "WINNT/mutx.c"
#include "WINNT/once.c"
#endif
