$argdecl = '';
$realunsigned = 0;
$needprefix = 0;
$bool = '';
$unsigned = '';
$signed = '';
$float = '';
$string = '';
$timeslot = '';
$usage = ' [--version]';
@allargs = ();
print "/* Automatically generated by mkargs - DO NOT EDIT! */\n";
print "/* Built by command: $0 ", join(' ', @ARGV), " */\n\n";
while (<>) {
	next if /^#/ || /^\s*$/;
	chop;
	if ($_ eq '-TiNGtrace') {	# special because global variable
		$unsigned .= "if ((ep = args_prefix(\"-TiNGtrace\", sp))) {\n";
		$unsigned .= "t = &TiNGtrace;\n";
		$unsigned .= "} else ";
		$needprefix = 1;
		next;
	}
	($code, $name, $type) = split;
	push(@allargs, $code);
	my $cdecl, $comp, $after;
	if (length($code) == 1) {
		$comp = "*sp == '$code'";
		$after = " ep = sp+1,";
	} else {
		$comp = '(ep = args_prefix("' . $code . '", sp))';
		$needprefix = 1;
		$after = '';
	}
	if ($type eq 'unsigned') {
		$argdecl .= "\tunsigned $name;\n";
		$unsigned .= "if ($comp)$after t = &ap->$name;\nelse ";
		$realunsigned = 1;
	} elsif ($type eq 'signed') {
		$argdecl .= "\tsigned $name;\n";
		$signed .= "if ($comp)$after t = &ap->$name;\nelse ";
	} elsif ($type eq 'float') {
		$argdecl .= "\tfloat $name;\n";
		$float .= "if ($comp)$after t = &ap->$name;\nelse ";
	} elsif ($type eq 'bool') {
		$argdecl .= "\tunsigned $name;\n";
		$bool .= "if ($comp)$after ap->$name = 1;\nelse ";
		$name = "=$name";
	} elsif ($type eq 'string') {
		$argdecl .= "\tchar *$name;\n";
		$string .= "if ($comp)$after t = &ap->$name;\nelse ";
	} elsif ($type eq 'timeslot') {
		$argdecl .= "\tMVIP $name;\n";
		$timeslot .= "if ($comp)$after t = &ap->$name;\nelse ";
	} else {
		die "Unknown option type: $type\n";
	}
	$usage .= " [-$code $name]";
}
if ($argdecl) {
	print "struct arguments {\n$argdecl};\n\n";
	print "#define ARGS_DECL static struct arguments arg;\n";
	print "#define ARGS_CALL (progname = *argv++),args(&arg, &argv)\n\n";
} else {
	print "#define ARGS_DECL \n";
	print "#define ARGS_CALL (progname = *argv++),args(&argv)\n\n";
}
print "#define ARGS_USAGE \"$usage\"\n\n";
print "char *progname;\n\n";

if ($needprefix) {
	&prettyprint(
		<<'EOF_pfx'
static char *args_prefix(const char *pfx, char *s)
{
	for (;;) {
		if (!*pfx) return s;
		if (*pfx++ != *s++) return 0;
	}
}

EOF_pfx
);
}

&prettyprint(
	<<'EOFN_B1'
static char *args_try_bool(struct arguments *ap, char *sp)
{
	for (; *sp;) {
		char *ep;
EOFN_B1
	. $bool
	. <<'EOFN_B2'
		break;
		sp = ep;
	}
	return sp;
}
EOFN_B2
) if $bool;

if ($argdecl && $realunsigned) {
	&prettyprint(
		<<'EOFN_U1a'
#include <stdlib.h>
static int args_try_unsigned(struct arguments *ap, char *sp, char ***argv)
{
	unsigned *t;
	char *ep;
EOFN_U1a
		. $unsigned
		. <<'EOFN_U2a'
	return 0;
	if (!*ep) {
		ep = *++*argv;
		if (!ep) {
			fprintf(stderr, "value missing for '%s'\n", *--*argv);
			return 1;
		}
	}
	*t = strtoul(ep, &ep, 0);
	if (*ep) {
		fprintf(stderr, "junk after value: '%s' for '%s'\n", ep, **argv);
		return 1;
	}
	return 2;
}

EOFN_U2a
	);
} else {
	&prettyprint(
		<<'EOFN_U1b'
#include <stdlib.h>
static int args_try_unsigned(char *sp, char ***argv)
{
	unsigned *t;
	char *ep;
EOFN_U1b
		. $unsigned
		. <<'EOFN_U2b'
	return 0;
	if (!*ep) {
		ep = *++*argv;
		if (!ep) {
			fprintf(stderr, "value missing for '%s'\n", *--*argv);
			return 1;
		}
	}
	*t = strtoul(ep, &ep, 0);
	if (*ep) {
		fprintf(stderr, "junk after value: '%s' for '%s'\n", ep, **argv);
		return 1;
	}
	return 2;
}

EOFN_U2b
	) if $unsigned;
}

&prettyprint(
	<<'EOFN_SI1'
#include <stdlib.h>
static int args_try_signed(struct arguments *ap, char *sp, char ***argv)
{
	signed *t;
	char *ep;
EOFN_SI1
	. $signed
	. <<'EOFN_SI2'
	return 0;
	if (!*ep) {
		ep = *++*argv;
		if (!ep) {
			fprintf(stderr, "value missing for '%s'\n", *--*argv);
			return 1;
		}
	}
	*t = strtol(ep, &ep, 0);
	if (*ep) {
		fprintf(stderr, "junk after value: '%s' for '%s'\n", ep, **argv);
		return 1;
	}
	return 2;
}

EOFN_SI2
) if $signed;

&prettyprint(
	<<'EOFN_FL1'
#include <stdlib.h>
static int args_try_float(struct arguments *ap, char *sp, char ***argv)
{
	float *t;
	char *ep;
EOFN_FL1
	. $float
	. <<'EOFN_FL2'
	return 0;
	if (!*ep) {
		ep = *++*argv;
		if (!ep) {
			fprintf(stderr, "value missing for '%s'\n", *--*argv);
			return 1;
		}
	}
	*t = strtod(ep, &ep);
	if (*ep) {
		fprintf(stderr, "junk after value: '%s' for '%s'\n", ep, **argv);
		return 1;
	}
	return 2;
}

EOFN_FL2
) if $float;

&prettyprint(
	<<'EOFN_S1'
static int args_try_string(struct arguments *ap, char *sp, char ***argv)
{
	char *ep, **t;
EOFN_S1
	. $string
	. <<'EOFN_S2'
	return 0;
	if (!*ep) {
		ep = *++*argv;
		if (!ep) {
			fprintf(stderr, "value missing for '%s'\n", *--*argv);
			return 1;
		}
	}
	*t = ep;
	return 2;
}

EOFN_S2
) if $string;

&prettyprint(
	<<'EOFN_T1'
#include <stdlib.h>
static int args_try_timeslot(struct arguments *ap, char *sp, char ***argv)
{
	MVIP *t;
	char *ep;
EOFN_T1
	. $timeslot
	. <<'EOFN_T2'
	return 0;
	if (!*ep) {
		ep = *++*argv;
		if (!ep) {
			fprintf(stderr, "value missing for '%s'\n", *--*argv);
			return 1;
		}
	}
	t->stream = strtol(ep, &ep, 0);
	if (*ep != ':') {
		fprintf(stderr, "expected ':' after stream, got '%s' for '%s'\n",
			ep, **argv);
		return 1;
	}
	t->timeslot = strtol(++ep, &ep, 0);
	if (*ep == ':') {
		if (*++ep == 'a') t->type = kSMTimeslotTypeALaw;
		else if (*ep == 'u') t->type = kSMTimeslotTypeMuLaw;
		else if (*ep == 'r') t->type = kSMTimeslotTypeData;
		else {
			fprintf(stderr, "unknown timeslot type: '%s' (expected 'a', 'u', or 'r') for '%s'\n", ep, **argv);
			return 1;
		}
		ep++;
	}
	if (*ep) {
		fprintf(stderr, "junk after value: '%s' for '%s'\n", ep, **argv);
		return 1;
	}
	return 2;
}

EOFN_T2
) if $timeslot;

if ($argdecl) {
	$argsfn = "static int args(struct arguments *ap, char ***argv)\n{\n"
} else {
	$argsfn = "static int args(char ***argv)\n{\n"
}
$argsfn .= <<'LOOPSTART';
	for (; **argv; ++*argv) {
		char *ep = **argv;
		if (*ep++ != '-' || !*ep) break;
		if (!strcmp(ep, "-version")) {
			fprintf(stderr, "%s: version %s\n", progname, version);
LOOPSTART
$argsfn .= "} else {\nint i;\n";
$argsfn .= "ep = args_try_bool(ap, ep);\n" if $bool;
$argsfn .= "if (!*ep) continue;\n";
$argsfn .= "if (!strcmp(ep, \"-\")) {\n++*argv;\nreturn 0;\n}\n";
$argsfn .= "if (1\n";
if ($unsigned) {
	if ($argdecl && $realunsigned) {
		$argsfn .= " && !(i = args_try_unsigned(ap, ep, argv))\n";
	} else {
		$argsfn .= " && !(i = args_try_unsigned(ep, argv))\n";
	}
}
$argsfn .= " && !(i = args_try_signed(ap, ep, argv))\n" if $signed;
$argsfn .= " && !(i = args_try_float(ap, ep, argv))\n" if $float;
$argsfn .= " && !(i = args_try_string(ap, ep, argv))\n" if $string;
$argsfn .= " && !(i = args_try_timeslot(ap, ep, argv))\n" if $timeslot;
$argsfn .= <<'LOOPEND';
			) {
				fprintf(stderr, "unrecognised option: %s\n", **argv);
				return 1;
			} else if (i != 2) return 1;
		}
	}
	return 0;
}
LOOPEND
&prettyprint($argsfn);
for (; @allargs;) {
	my $prev = shift(@allargs);
	my $lp = length($prev);
	my $arg;
	for $arg (@allargs) {
		my $la = length($arg);
		if ($lp <= $la
			&& substr($prev, 0, $lp) eq substr($arg, 0, $lp)) {
			print "\n#error ambiguous options: '$prev' and '$arg'\n";
			print STDERR "Error: ambiguous options: '$prev' and '$arg'\n";
		}
	}
}

sub prettyprint {
	my $code = $_[0];
	my $indent = 0;
	$code =~ s/\t//g;
	for (;;) {
		if ($code =~ s/^([^{}()\n]*[{(])//) {
			print $1;
			$indent++;
		} elsif ($code =~ s/^([^{}()\n]*[})])//) {
			print $1;
			$indent--;
		} elsif ($code =~ s/^([^{}()\n]*\n)([)}])//) {
			$indent--;
			print $1, "\t" x $indent, $2;
		} elsif ($code =~ s/^([^{}()\n]*\n)//) {
			print $1;
			print "\t" x $indent;
		} else {
			print $code;
			last;
		}
	}
}
