LINK_OBJS= $(PROG_OBJS) $(PROG_THIS_OBJS) $(SHARED_OBJS) $(SHARED_THIS_OBJS)

PROG_INCLUDES=  \
	-I../../../include \
	-I../../../include

PROG_THIS_CC_DEFINES= \
	-D_REENTRANT

$(GEN)/incall: ../../gen/version.i gen/incall.args.i $(LINK_OBJS)
	$(LINK) $(LINK_OBJS) -lpthread $(LIBS) $(LIBS_COMMON) $(LIBS_SW) $(LIBS_CL) 2>&1 | t0 errs/$@

all-$(TiNGTARGET): $(GEN)/incall
