#ifndef CARDINFOD_INTERFACE_H
#define CARDINFOD_INTERFACE_H

#define CARDINFO_CMD_MODLIST "modlist\n"
#define CARDINFO_CMD_TDMLIST "tdmlist\n"

#define CARDINFO_CMD_CARDINFO "cardinfo\n"
#define CARDINFO_CARD_TYPE_SIMULATION "0"
#define CARDINFO_CARD_TYPE_SIMULATION_NUM 0
#define CARDINFO_CARD_TYPE_PX "1"
#define CARDINFO_CARD_TYPE_PX_NUM 1
#define CARDINFO_CARD_TYPE_PSV3 "2"
#define CARDINFO_CARD_TYPE_PSV3_NUM 2

#define CARDINFO_CMD_MODADDR "modaddr\t"

#define CARDINFO_OK '+'
#define CARDINFO_OK_STR "+"

#define CARDINFO_BAD_RESPONSE_HEAD "-Commands;"
#define CARDINFO_BAD_RESPONSE_CHECK_LEN 9

#endif
