# Note that this makefile describes how to build various programs for
# various systems. These are:
#
#	System	Compiler	Abbreviation in variables etc.
#	------	--------	------------------------------
#	Solaris	gcc		GCC
#
# The system is selected by the TiNGTARGET environment variable.

GCC_COMPILE=gcc $(CFLAGS_LINUX_V6) -O2 -c -MD -o "$@" $< 2>&1 | t0 errs/$@; perl ../../libutil/fixdep.pl $@
LIBS=-lm -lpthread -lrt
LIBS_COMMON= -lacu_res
LIBS_CL= -lacu_cl
LIBS_SW= -lacu_sw

CFLAGS_LINUX_V6= \
	$(CFLAGS_CPU) \
	-fPIC \
	$(CC_DEFINES) \
	-DTiNGTYPE_LINUX \
	$(PROG_CC_DEFINES) \
	$(PROG_LINUX_V6_CC_DEFINES) \
	-DACU_LINUX_V6 \
	-DLINUX \
	-DUNIX_SYSTEM \
	$(INCLUDES) \
	-I../../../include \
	$(PROG_INCLUDES) \
	-Wall \
	-W \
	-Wshadow \
	-Wpointer-arith \
	-Wstrict-prototypes \
	-Wmissing-prototypes \
	-g \
	-O

TiNG_LIB = \
	../../apilib/$(GEN)/TiNGlib.o

CALL_LIB =

SWITCH_LIB =

-include $(GEN)/objs.mak

# static rules

$(PROG_OBJS): $(GEN)/%.o: %.c $(GEN)/.exists errs/$(GEN)/.exists
	$(GCC_COMPILE)

$(PROG_LINUX_V6_OBJS): $(GEN)/%.o:LINUX/%.c $(GEN)/.exists errs/$(GEN)/.exists
	$(GCC_COMPILE)

$(GEN)/%.s: %.c $(GEN)/.exists errs/$(GEN)/.exists
	gcc $(CFLAGS_LINUX) -O2 -S -c -MD -o "$@" $< 2>&1 | t0 errs/$@; perl ../../libutil/fixdep.pl $@

-include /dev/null $(shell find $(GEN) -name \*.M)
