LINK_OBJS= $(PROG_OBJS) $(PROG_THIS_OBJS) $(SHARED_OBJS) $(SHARED_THIS_OBJS)

PROG_THIS_CC_DEFINES= \
	-D_REENTRANT

$(GEN)/rtpclerk: ../../gen/version.i gen/rtpclerk.args.i $(LINK_OBJS)
	$(LINK) $(LINK_OBJS) -lpthread $(LIBS) 2>&1 | t0 errs/$@

all-$(TiNGTARGET):  $(GEN)/rtpclerk
