#!/usr/local/bin/perl
# getdep.pl - find dependency information in output of Sun Workshop C compiler
#
# The dependency information (generated by the -H option) is mixed in with
# the errors. They can be distinguished by the rather ugly hack of testing
# each line of output to see if it is the name of an existing file. 
# If you have a file whose name happens to be an error message, it won't
# appear on the dependency list.

die "Usage: getdep.pl target errsfile\n" unless @ARGV == 2;
my $target = $ARGV[0];
my $errsfile = $ARGV[1];
open(DEPS, ">$target.M") || die "Cannot create depfile: $target.M: $!\n";
open(ERRS, ">$errsfile") || die "Cannot create errsfile: $errsfile: $!\n";
@deps = ();
$errs = 0;
while (<STDIN>) {
	my $o = $_;
	chop;
	s/^\t*//;
	if (-f $_) {
		push(@deps, $_);
	} else {
		print $o;
		print ERRS $o;
		$errs = 1;
	}
}
print DEPS $target, ": \\\n\t", join(" \\\n\t", &uniq(sort(@deps))), "\n";
close(DEPS);
close(ERRS);
if (!$errs) {
	unlink($errsfile) || die "Cannot delete empty errs file: $errsfile: $!\n";
}

sub uniq {
	my @s = @_;
	my $prev = '';
	my @o = ();
	my $v;
	for $v (@s) {
		next if $v eq $prev;
		push(@o, $v);
		$prev = $v;
	}
	return @o;
}
