$argdecl = '';
$realunsigned = 0;
$needprefix = 0;
$bool = '';
$unsigned = '';
$signed = '';
$float = '';
$string = '';
$timeslot = '';
$range = '';
@allargs = ();
print "/* Automatically generated by mkargs - DO NOT EDIT! */\n";
print "/* Built by command: $0 ", join(' ', @ARGV), " */\n\n";
if ($ARGV[0] eq '-v') {
	die "Usage: mkargs [-v version-file [-r relver-file]] files...\n" unless @ARGV > 1;
	shift(@ARGV);
	$verfile = shift(@ARGV);
	open(V, $verfile) || die "Cannot open file: $verfile: $!\n";
	$version = <V>;
	close(V);
	chomp($version);
	if ($ARGV[0] eq '-r') {
		die "Usage: mkargs [-v version-file [-r relver-file]] files...\n" unless @ARGV > 1;
		shift(@ARGV);
		$relverfile = shift(@ARGV);
		open(V, $relverfile) || die "Cannot open file: $relverfile: $!\n";
		$relver = <V>;
		close(V);
		chomp($relver);
	}
	$usage = ' [--version]';
} else {
	$usage = '';
}
while (<>) {
	next if /^#/ || /^\s*$/;
	chop;
	if ($_ eq '-TiNGtrace') {	# special because global variable
		$unsigned .= "if ((ep = args_prefix(\"-TiNGtrace\", sp))) {\n";
		$unsigned .= "t = &TiNGtrace;\n";
		$unsigned .= "} else ";
		$needprefix = 1;
		next;
	} elsif ($_ eq '-TiNGthreadtrace') {
		$string .= "if ((ep = args_prefix(\"-TiNGthreadtrace\", sp))) {\n";
		$string .= "if (!*ep) ep = *++*argv;\n";
		$string .= "if (!ep) return ARGS_BAD_NOARG;\n";
		$string .= "TiNGtrace_file_perthread(ep);\n";
		$string .= "return ARGS_OK;\n";
		$string .= "} else ";
		$needprefix = 1;
		next;
	}
	push(@arglist, $_);
}
for (sort {$b cmp $a} (@arglist)) {
	my ($code, $name, $type) = split;
	push(@allargs, $code);
	my $cdecl;
	my $comp;
	my $after;
	if (length($code) == 1) {
		$comp = "*sp == '$code'";
		$after = " ep = sp+1,";
	} else {
		$comp = '(ep = args_prefix("' . $code . '", sp))';
		$needprefix = 1;
		$after = '';
	}
	if ($type eq 'unsigned') {
		$argdecl .= "\tunsigned $name;\n";
		$unsigned .= "if ($comp)$after t = &ap->$name;\nelse ";
		$realunsigned = 1;
	} elsif ($type eq 'signed') {
		$argdecl .= "\tsigned $name;\n";
		$signed .= "if ($comp)$after t = &ap->$name;\nelse ";
	} elsif ($type eq 'float') {
		$argdecl .= "\tfloat $name;\n";
		$float .= "if ($comp)$after t = &ap->$name;\nelse ";
	} elsif ($type eq 'bool') {
		$argdecl .= "\tunsigned $name;\n";
		$bool .= "if ($comp)$after ap->$name = 1;\nelse ";
		$name = "=$name";
	} elsif ($type eq 'string') {
		$argdecl .= "\tchar *$name;\n";
		$string .= "if ($comp)$after t = &ap->$name;\nelse ";
	} elsif ($type eq 'timeslot') {
		$argdecl .= "\tMVIP $name;\n";
		$timeslot .= "if ($comp)$after t = &ap->$name;\nelse ";
	} elsif ($type eq 'range') {
		$argdecl .= "\tRANGE $name;\n";
		$range .= "if ($comp)$after r = &ap->$name;\nelse ";
	} else {
		die "Unknown option type: $type\n" if $type ne '';
		die "Unknown special option : $name\n";
	}
	$usage .= " [-$code $name]";
}
if ($argdecl) {
	print "struct arguments {\n$argdecl};\n\n";
	print "#define ARGS_DECL static struct arguments arg;\n";
	print "#define ARGS_CALL (progname = *argv++),args(&arg, &argv)\n\n";
} else {
	print "#define ARGS_DECL \n";
	print "#define ARGS_CALL (progname = *argv++),args(&argv)\n\n";
}
print "#define ARGS_USAGE \"$usage\"\n\n";
print "char *progname;\n\n";
if (defined($version)) {
	print "static const char version[] = \"@(#)\$from: \" __FILE__ \" ";
	print "Aculab Telephony Software V$relver." if defined($relver);
	print "$version \$\";\n\n";
}

print <<EOF;
#include <string.h>

enum args_result {
	ARGS_NOMATCH,
	ARGS_OK,
	ARGS_BAD_NOMSG,
	ARGS_BAD_NOARG,
};

EOF

if ($needprefix) {
	&prettyprint(
		<<'EOF_pfx'
static char *args_prefix(const char *pfx, char *s)
{
	for (;;) {
		if (!*pfx) return s;
		if (*pfx++ != *s++) return 0;
	}
}

EOF_pfx
);
}

&prettyprint(
	<<'EOFN_B1'
static char *args_try_bool(struct arguments *ap, char *sp)
{
	for (; *sp;) {
		char *ep;
EOFN_B1
	. $bool
	. <<'EOFN_B2'
		break;
		sp = ep;
	}
	return sp;
}

EOFN_B2
) if $bool;

if ($argdecl && $realunsigned) {
	&prettyprint(
		<<'EOFN_U1a'
#include <stdlib.h>

static enum args_result args_try_unsigned(struct arguments *ap, char *sp, char ***argv)
{
	unsigned *t;
	char *tp;	// temporary only needed to avoid gcc warning
	char *ep;
EOFN_U1a
		. $unsigned
		. <<'EOFN_U2a'
	return ARGS_NOMATCH;
	if (!*ep) {
		ep = *++*argv;
		if (!ep) return ARGS_BAD_NOARG;
	}
	tp = ep;	// only needed to avoid 'may be undefined' gcc warning
	*t = strtoul(tp, &ep, 0);
	if (*ep) {
		fprintf(stderr, "junk after value: '%s' for '%s'\n", ep, **argv);
		return ARGS_BAD_NOMSG;
	}
	return ARGS_OK;
}

EOFN_U2a
	);
} else {
	&prettyprint(
		<<'EOFN_U1b'
#include <stdlib.h>
static enum args_result args_try_unsigned(char *sp, char ***argv)
{
	unsigned *t;
	char *tp;	// temporary only needed to avoid gcc warning
	char *ep;
EOFN_U1b
		. $unsigned
		. <<'EOFN_U2b'
	return ARGS_NOMATCH;
	if (!*ep) {
		ep = *++*argv;
		if (!ep) return ARGS_BAD_NOARG;
	}
	tp = ep;	// only needed to avoid 'may be undefined' gcc warning
	*t = strtoul(tp, &ep, 0);
	if (*ep) {
		fprintf(stderr, "junk after value: '%s' for '%s'\n", ep, **argv);
		return ARGS_BAD_NOMSG;
	}
	return ARGS_OK;
}

EOFN_U2b
	) if $unsigned;
}

&prettyprint(
	<<'EOFN_SI1'
#include <stdlib.h>
static enum args_result args_try_signed(struct arguments *ap, char *sp, char ***argv)
{
	signed *t;
	char *tp;	// temporary only needed to avoid gcc warning
	char *ep;
EOFN_SI1
	. $signed
	. <<'EOFN_SI2'
	return ARGS_NOMATCH;
	if (!*ep) {
		ep = *++*argv;
		if (!ep) return ARGS_BAD_NOARG;
	}
	tp = ep;	// only needed to avoid 'may be undefined' gcc warning
	*t = strtol(tp, &ep, 0);
	if (*ep) {
		fprintf(stderr, "junk after value: '%s' for '%s'\n", ep, **argv);
		return ARGS_BAD_NOMSG;
	}
	return ARGS_OK;
}

EOFN_SI2
) if $signed;

&prettyprint(
	<<'EOFN_FL1'
#include <stdlib.h>
static enum args_result args_try_float(struct arguments *ap, char *sp, char ***argv)
{
	float *t;
	char *tp;	// temporary only needed to avoid gcc warning
	char *ep;
EOFN_FL1
	. $float
	. <<'EOFN_FL2'
	return ARGS_NOMATCH;
	if (!*ep) {
		ep = *++*argv;
		if (!ep) return ARGS_BAD_NOARG;
	}
	tp = ep;	// only needed to avoid 'may be undefined' gcc warning
	*t = strtod(tp, &ep);
	if (*ep) {
		fprintf(stderr, "junk after value: '%s' for '%s'\n", ep, **argv);
		return ARGS_BAD_NOMSG;
	}
	return ARGS_OK;
}

EOFN_FL2
) if $float;

&prettyprint(
	<<'EOFN_S1'
static enum args_result args_try_string(struct arguments *ap, char *sp, char ***argv)
{
	char *ep, **t;
EOFN_S1
	. $string
	. <<'EOFN_S2'
	return ARGS_NOMATCH;
	if (!*ep) {
		ep = *++*argv;
		if (!ep) return ARGS_BAD_NOARG;
	}
	*t = ep;
	return ARGS_OK;
}

EOFN_S2
) if $string;

&prettyprint(
	<<'EOFN_T1'
#include <stdlib.h>
static enum args_result args_try_timeslot(struct arguments *ap, char *sp, char ***argv)
{
	MVIP *t;
	char *tp;	// temporary only needed to avoid gcc warning
	char *ep;
EOFN_T1
	. $timeslot
	. <<'EOFN_T2'
	return ARGS_NOMATCH;
	if (!*ep) {
		ep = *++*argv;
		if (!ep) return ARGS_BAD_NOARG;
	}
	tp = ep;	// only needed to avoid 'may be undefined' gcc warning
	t->stream = strtol(tp, &ep, 0);
	if (*ep != ':') {
		fprintf(stderr, "expected ':' after stream, got '%s' for '%s'\n",
			ep, **argv);
		return ARGS_BAD_NOMSG;
	}
	tp = ++ep;	// only needed to avoid 'may be undefined' gcc warning
	t->timeslot = strtol(tp, &ep, 0);
	if (*ep == ':') {
		if (*++ep == 'a') t->type = kSMTimeslotTypeALaw;
		else if (*ep == 'u') t->type = kSMTimeslotTypeMuLaw;
		else if (*ep == 'r') t->type = kSMTimeslotTypeData;
		else {
			fprintf(stderr, "unknown timeslot type: '%s' (expected 'a', 'u', or 'r') for '%s'\n", ep, **argv);
			return ARGS_BAD_NOMSG;
		}
		ep++;
	}
	if (*ep) {
		fprintf(stderr, "junk after value: '%s' for '%s'\n", ep, **argv);
		return ARGS_BAD_NOMSG;
	}
	return ARGS_OK;
}

EOFN_T2
) if $timeslot;

&prettyprint(
	<<'EOFN_R1'
#include <stdlib.h>
static int args_try_range(struct arguments *ap, char *sp, char ***argv)
{
	RANGE *r;
	char *tp;	// temporary only needed to avoid gcc warning
	char *ep;
EOFN_R1
	. $range
	. <<'EOFN_R2'
	return ARGS_NOMATCH;
	if (!*ep) {
		ep = *++*argv;
		if (!ep) return ARGS_BAD_NOARG;
	}
	tp = ep;	// only needed to avoid 'may be undefined' gcc warning
	r->min = strtol(tp, &ep, 0);
	if (*ep != ':') {
		fprintf(stderr, "expected ':' after mimimum, got '%s' for '%s'\n",
			ep, **argv);
		return ARGS_BAD_NOMSG;
	}
	tp = ++ep;	// only needed to avoid 'may be undefined' gcc warning
	r->max = strtol(tp, &ep, 0);
	if (*ep) {
		fprintf(stderr, "junk after maximum value: '%s' for '%s'\n", ep, **argv);
		return ARGS_BAD_NOMSG;
	}
	return ARGS_OK;
}

EOFN_R2
) if $range;

if ($argdecl) {
	$argsfn = "static int args(struct arguments *ap, char ***argv)\n{\n"
} else {
	$argsfn = "static int args(char ***argv)\n{\n"
}
$argsfn .= <<'LOOPSTART';
	for (; **argv; ++*argv) {
		char *ep = **argv;
		if (*ep++ != '-' || !*ep) break;
		if (0) {
LOOPSTART
$argsfn .= <<VERCODE if defined($version);
		} else if (!strcmp(ep, "-version")) {
			fprintf(stderr, "%s: version %s\\n", progname, version);
VERCODE
$argsfn .= "} else {\nint i;\n";
$argsfn .= "ep = args_try_bool(ap, ep);\n" if $bool;
$argsfn .= "if (!*ep) continue;\n";
$argsfn .= "if (!strcmp(ep, \"-\")) {\n++*argv;\nreturn 0;\n}\n";
$argsfn .= "if (1\n";
if ($unsigned) {
	if ($argdecl && $realunsigned) {
		$argsfn .= " && !(i = args_try_unsigned(ap, ep, argv))\n";
	} else {
		$argsfn .= " && !(i = args_try_unsigned(ep, argv))\n";
	}
}
$argsfn .= " && !(i = args_try_signed(ap, ep, argv))\n" if $signed;
$argsfn .= " && !(i = args_try_float(ap, ep, argv))\n" if $float;
$argsfn .= " && !(i = args_try_string(ap, ep, argv))\n" if $string;
$argsfn .= " && !(i = args_try_timeslot(ap, ep, argv))\n" if $timeslot;
$argsfn .= " && !(i = args_try_range(ap, ep, argv))\n" if $range;
$argsfn .= <<'LOOPEND';
			) {
				fprintf(stderr, "unrecognised option: %s\n", **argv);
				return 1;
			} else switch (i) {
			case ARGS_OK: break;
			case ARGS_BAD_NOMSG: return 1;
			case ARGS_BAD_NOARG:
				fprintf(stderr, "value missing for '%s'\n", **argv);
				return 1;
			}
		}
	}
	return 0;
}
LOOPEND
&prettyprint($argsfn);
for (; @allargs;) {
	my $prev = shift(@allargs);
	my $lp = length($prev);
	my $arg;
	for $arg (@allargs) {
		my $la = length($arg);
		if ($lp <= $la
			&& substr($prev, 0, $lp) eq substr($arg, 0, $lp)) {
			print "\n#error ambiguous options: '$prev' and '$arg'\n";
			print STDERR "Error: ambiguous options: '$prev' and '$arg'\n";
		}
	}
}

sub prettyprint {
	my $code = $_[0];
	my $indent = 0;
	$code =~ s/\t//g;
	for (;;) {
		if ($code =~ s/^([^{}()\n]*[{(])//) {
			print $1;
			$indent++;
		} elsif ($code =~ s/^([^{}()\n]*[})])//) {
			print $1;
			$indent--;
		} elsif ($code =~ s/^([^{}()\n]*\n)([)}])//) {
			$indent--;
			print $1, "\t" x $indent, $2;
		} elsif ($code =~ s/^([^{}()\n]*\n)//) {
			print $1;
			print "\t" x $indent;
		} else {
			print $code;
			last;
		}
	}
}
